---
version: '3.9'

services:
  front:
    image: nginx
    working_dir: /opt/src
    ports:
      - "8000:80"
    volumes:
      - ./nginx:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
     
    links:
        - php
  php:
    image: php:8-fpm
    volumes:
        - ./nginx:/var/www/html
        - /opt/files:/opt/files
  back:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /opt/files:/opt/files
      - ./credentials:/root/.aws/credentials
